# Generated by Django 5.1.1 on 2024-10-09 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawFirm', '0001_initial'),
        ('User', '0002_user_user_type_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='law_firm_profile', to='User.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('practice_areas', models.JSONField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('education', models.TextField()),
                ('achievements', models.TextField()),
                ('law_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LawFirm.lawfirm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to='User.user')),
            ],
        ),
    ]
