# Generated by Django 5.1.2 on 2024-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawFirm', '0002_lawfirm_user_lawyerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='practice_areas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
