# Generated by Django 5.1.2 on 2024-10-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawFirm', '0004_alter_lawyerprofile_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirm',
            name='practice_areas',
            field=models.CharField(blank=True, choices=[('Civil Law', 'Civil Law'), ('Corporate Law', 'Corporate Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law'), ('Tax Law', 'Tax Law')], default=True),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='practice_areas',
            field=models.CharField(blank=True, choices=[('Civil Law', 'Civil Law'), ('Corporate Law', 'Corporate Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law'), ('Tax Law', 'Tax Law')], default=True),
        ),
    ]
