# Generated by Django 5.1.2 on 2024-10-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawFirm', '0006_alter_lawyerprofile_practice_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawfirm',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='classification',
            field=models.CharField(blank=True, choices=[('local', 'محلي'), ('global', 'عالمي')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='law_firms/covers/'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='founder_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='law_firms/logos/'),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='practice_areas',
            field=models.CharField(blank=True, choices=[('Civil Law', 'Civil Law'), ('Corporate Law', 'Corporate Law'), ('Criminal Law', 'Criminal Law'), ('Family Law', 'Family Law'), ('Tax Law', 'Tax Law')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='services',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='social_media_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawfirm',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
