# Generated by Django 5.1.2 on 2024-11-03 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawFirm', '0008_alter_lawfirm_practice_areas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='law_firm_onwer', to=settings.AUTH_USER_MODEL),
        ),
    ]
