# Generated by Django 5.1.1 on 2024-10-06 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LawFirm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField()),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultants', to='LawFirm.lawfirm')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('family', 'أسري'), ('administrative', 'إداري'), ('criminal', 'جنائي'), ('investment', 'استثمار')], max_length=50)),
                ('content', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'مفعلة'), ('inactive', 'غير مفعلة')], default='active', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawFirm.lawfirm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
