# Generated by Django 5.1.1 on 2024-10-06 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LawFirm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('benefits', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('application_link', models.URLField()),
                ('law_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawFirm.lawfirm')),
            ],
        ),
    ]
